// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAo11iWpPVEk5K6I8QupY1K_7nbmZcEQ',
    appId: '1:690684627465:web:fdca24e98ac1bc04bd46d8',
    messagingSenderId: '690684627465',
    projectId: 'pothole-detection-app-70f78',
    authDomain: 'pothole-detection-app-70f78.firebaseapp.com',
    storageBucket: 'pothole-detection-app-70f78.firebasestorage.app',
    measurementId: 'G-Y5FRWG9KRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pwEMxMAmD1bE5twIx9fGZfOVcNtfkKw',
    appId: '1:690684627465:android:661859efe5bbd75dbd46d8',
    messagingSenderId: '690684627465',
    projectId: 'pothole-detection-app-70f78',
    storageBucket: 'pothole-detection-app-70f78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldGslIv1NWpVsY9JOi1Wd2OOhwzrbxj0',
    appId: '1:690684627465:ios:ad0bea1916a1c4bbbd46d8',
    messagingSenderId: '690684627465',
    projectId: 'pothole-detection-app-70f78',
    storageBucket: 'pothole-detection-app-70f78.firebasestorage.app',
    iosBundleId: 'com.example.paveguardNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldGslIv1NWpVsY9JOi1Wd2OOhwzrbxj0',
    appId: '1:690684627465:ios:ad0bea1916a1c4bbbd46d8',
    messagingSenderId: '690684627465',
    projectId: 'pothole-detection-app-70f78',
    storageBucket: 'pothole-detection-app-70f78.firebasestorage.app',
    iosBundleId: 'com.example.paveguardNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAo11iWpPVEk5K6I8QupY1K_7nbmZcEQ',
    appId: '1:690684627465:web:beee971d81cb5386bd46d8',
    messagingSenderId: '690684627465',
    projectId: 'pothole-detection-app-70f78',
    authDomain: 'pothole-detection-app-70f78.firebaseapp.com',
    storageBucket: 'pothole-detection-app-70f78.firebasestorage.app',
    measurementId: 'G-LD08C7WRZX',
  );
}
